### ISSUE TITLE
Transactions should have a `details` button that drops down to show more information

### ISSUE THREAD

**Issue by krruzic** [turtlecoin/miniwallet-preact#2]
This detail should show the fee, the payment ID, the block height and any other info we have in the transaction object

**Comment by krruzic** [comment]
https://github.com/krruzic/miniwallet-preact/tree/add_tx_details
![image](https://user-images.githubusercontent.com/4000854/110201666-9ee8a780-7e21-11eb-8e57-24abe9f753f0.png)

**Comment by ExtraHash** [comment]
Maybe we should make an api call to the trtlpay api and fetch all of the details when they expand. We're a bit limited as far as what we have in the wallet backend

**Comment by zpalmtree** [comment]
idk what you're limited by
